export { default as Navigation } from "./Navigation";
export { default as Bio } from "./Bio";
export { default as Footer } from "./Footer";
export { default as Main } from "./Main";
export { default as Career } from "./Career";
export { default as Education } from "./Education";
export { default as Contact } from "./Contact";
export { default as Accreditations } from "./Accreditations";
export { default as Expertise } from "./Expertise";